# Generated by Django 4.1.6 on 2024-02-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_director_phone_alter_client_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(default='', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='client',
            name='director_phone',
            field=models.CharField(default='', max_length=256, verbose_name='Телефон собственника'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullName',
            field=models.CharField(default='', max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='manager_phone',
            field=models.CharField(default='', max_length=256, verbose_name='Телефон менеджера'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name_point',
            field=models.CharField(default='', max_length=256, verbose_name='Название торговой точки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='region',
            field=models.CharField(default='', max_length=256, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='client',
            name='with_work',
            field=models.CharField(default='', max_length=600, verbose_name='С кем работает'),
        ),
    ]
